server:
  port: 7002
  error.include-message: always

logging:
  level:
    root: INFO
    hcl.poc.productservice: DEBUG

spring:

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/reviewdb
    username: poc
    password: poc

  jpa:
    hibernate:
      ddl-auto: create-drop

management:
  endpoints:
    web:
      exposure:
        include: info, shutdown, health, env
  endpoint:
    shutdown:
      sensitive: false
      enabled: true

---
spring.config.activate.on-profile: docker

server:
  port: 8080

spring:
  datasource:
    dialect: org.hibernate.dialect.MySQL8Dialect
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mysqldb:3306/reviewdb?autoReconnect=true
    username: poc
    password: poc

  jpa:
    hibernate:
      ddl-auto: create-drop
