server:
  port: 7004

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/userdb
    username: poc
    password: poc

  jpa:
    hibernate:
      ddl-auto: create-drop

management:
  endpoints:
    web:
      exposure:
        include: info, shutdown, health, env
  endpoint:
    shutdown:
      sensitive: false
      enabled: true

