server:
  host: localhost
  port: 7000
  error.include-message: always

management:
  endpoints:
    web:
      exposure:
        include: info, shutdown, health, env
  endpoint:
    shutdown:
      sensitive: false
      enabled: true

app:
  product-service:
    host: localhost
    port: 7001
  recommendation-service:
    host: localhost
    port: 7003
  review-service:
    host: localhost
    port: 7002

logging:
  level:
    root: INFO
    com.light: DEBUG

---
spring.config.activate.on-profile: docker

server.port: 8080

app:
  product-service:
    host: product
    port: 8080
  recommendation-service:
    host: recommendation
    port: 8080
  review-service:
    host: review
    port: 8080
